# Generated by Django 4.1.1 on 2022-10-27 12:47

import API.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_rename_quest_can_pause_room_guest_can_pause_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=API.models.generate_unique_code, max_length=8, unique=True),
        ),
    ]
